module.exports = Object.freeze({
    INVALID_STATUS_CODE: 500,
    OK_STATUS_CODE: 200,
    ERROR_STATUS_CODE: 404,
    FORBIDDEN_STATUS_CODE: 403,
    UNAUTHORIZED_STATUS_CODE: 401,
    INCREMENTAL_POPULARITY_VALUE: 1,
    POPULARITY_SCORE_ZERO: 0,
    PORT_4000: 4000
});

